target 'Auth0Client', :exclusive => true do
  pod "Auth0Client", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Auth0Client", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
