name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'
        bundler-cache: true

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode }}
