# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "basic-sample" do
    pod "Auth0.iOS", :path => "../../"
    pod "SDWebImage", "~> 3.7.1"
end

target "basic-sampleTests" do

end
