# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "basic-sample" do
  pod "Auth0.iOS", "~> 1.0.0-beta"
end

target "basic-sampleTests" do

end
