platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TouchID' do

pod "Lock", "~> 1.4"
pod "Lock/TouchID"
pod "SimpleKeychain", "~> 0.2"

pod "Facebook-iOS-SDK", :inhibit_warnings => true #Ignore warnings for this lib
pod "ISO8601DateFormatter", :inhibit_warnings => true #Ignore warnings for this lib
pod "libextobjc", :inhibit_warnings => true #Ignore warnings for this lib
pod "BDBOAuth1Manager", :inhibit_warnings => true #Ignore warnings for this lib

end

target 'TouchIDTests' do

end

