platform :ios, "7.0"

inhibit_all_warnings!

target "Auth0Cognito" do
	pod "Lock", "~> 1.10"
  pod "SDWebImage", "~> 3.7"
  pod "JWTDecode", "~> 0.2"
  pod "SimpleKeychain", "~> 0.3"
  pod "MBProgressHUD", "~> 0.9"
  pod 'AWSCognitoSync', "~> 1.0"
end
