platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AWS' do

pod 'Lock'
pod 'SimpleKeychain'
pod 'AWSiOSSDKv2', '~> 2.0'
pod 'libextobjc', :inhibit_warnings => true #Ignore warnings for this lib
pod 'BDBOAuth1Manager', :inhibit_warnings => true #Ignore warnings for this lib
pod 'Facebook-iOS-SDK', :inhibit_warnings => true #Ignore warnings for this lib
pod 'ISO8601DateFormatter', :inhibit_warnings => true #Ignore warnings for this lib

end
