opt_out_usage

fastlane_version "1.95.0"

default_platform :ios

platform :ios do

  private_lane :dependencies do
    carthage(platform: "iOS", use_binaries: false, platform: "iOS")
  end

  lane :bootstrap do
    dependencies()
    match(git_url: "git@github.com:auth0/apple-certificates.git", type: "development")
  end

  lane :perform_release do
    publish_release()
  end

  lane :prepare_next_version do |options|
    prepare_release(bump: options[:bump], repository: 'Lock.iOS-OSX', version: options[:version], xcodeproj: 'Lock.xcodeproj')
  end

  lane :cache_update do
    sh "cd ..; bundle exec carthage_cache publish -f --bucket-name #{ENV["CARTHAGE_CACHE_BUCKET_NAME"]}"
  end

  private_lane :carthage_cache_exist do
    sh "cd ..; bundle exec carthage_cache exist --bucket-name #{ENV["CARTHAGE_CACHE_BUCKET_NAME"]}"
  end

  private_lane :carthage_cache_install do
    sh "cd ..; bundle exec carthage_cache install --verbose --bucket-name #{ENV["CARTHAGE_CACHE_BUCKET_NAME"]}"
  end
end