#!/bin/bash

set -e

source script/.env
source script/common/carthage

if [ -f Cartfile.resolved ] && type carthage > /dev/null
then
  check_carthage_version
  call_carthage "update"
elif [ -f Podfile ]
then
  if type bundle > /dev/null && bundle show pod > /dev/null
  then
    bundle exec pod update
  else
    pod update
  fi
fi
