source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Lock', :exclusive => true do
  pod 'Lock', :path => '../', :subspecs => ['ReactiveCore', '1Password', 'Safari', 'WebView', 'TouchID', 'Email', 'SMS']
  pod 'Lock-Facebook', '~> 2.0'

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'JWTDecode', '~> 0.2.1'
  pod 'SimpleKeychain'
end

target 'Tests', :exclusive => true do
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
  pod 'OHHTTPStubs'
  pod 'ObjectiveSugar'
  pod 'OCHamcrest', :inhibit_warnings => true #Ignore warnings for this lib
end
