source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Lock', :exclusive => true do
  pod 'Lock', :path => '../'
  pod 'Lock/TouchID', :path => '../'
  pod 'Lock/SMS', :path => '../'
  pod 'Lock/ReactiveCore', :path => '../'
  pod 'Lock/GooglePlus', :path => '../'
  pod 'libextobjc', :inhibit_warnings => true #Ignore warnings for this lib
  pod 'BDBOAuth1Manager', :inhibit_warnings => true #Ignore warnings for this lib
  pod 'JWTDecode'
  pod 'SimpleKeychain'
end

target 'Tests', :exclusive => true do
  pod 'Lock', :path => '../'
  pod 'Lock/TouchID', :path => '../'
  pod 'Lock/SMS', :path => '../'
  pod 'libextobjc', :inhibit_warnings => true #Ignore warnings for this lib
  pod 'BDBOAuth1Manager', :inhibit_warnings => true #Ignore warnings for this lib

  pod 'Specta', '~> 0.3.2'
  pod 'Expecta'
  pod 'OCMockito'
  pod 'OHHTTPStubs'
end
