name: CI
on:
    pull_request:
      types:
        - opened
        - synchronize

jobs:
    test:
        name: Test using Xcode ${{ matrix.xcode }}
        runs-on: macos-latest

        env:
            xcodeproj: Lock.xcodeproj
            scheme: Lock

        strategy:
          matrix:
            xcode: 
              - '14.1'

        steps:
            - name: Checkout
              uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

            - name: Set up environment
              uses: ./.github/actions/setup
              with:
                xcode: ${{ matrix.xcode }}

            - name: Run tests
              uses: ./.github/actions/test
              with:
                xcode: ${{ matrix.xcode }}
                scheme: ${{ env.scheme }}
                platform: iOS

            - name: Convert coverage report
              run: bundle exec slather coverage -x --scheme ${{ env.scheme }} ${{ env.xcodeproj }}

            - name: Upload coverage report
              uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457

            - name: Cancel wokflow on failure
              uses: andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a
              if: ${{ failure() }}

    pod-lint:
        name: Lint podspec using Xcode ${{ matrix.xcode }}
        runs-on: macos-latest

        strategy:
          matrix:
            xcode: 
              - '14.1'

        steps:
            - name: Checkout
              uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

            - name: Set up environment
              uses: ./.github/actions/setup
              with:
                xcode: ${{ matrix.xcode }}

            - name: Run pod lib lint
              run: bundle exec pod lib lint --allow-warnings --fail-fast

            - name: Cancel wokflow on failure
              uses: andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a
              if: ${{ failure() }}

    swiftlint:
        name: Lint code with SwiftLint
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

            - name: Run SwiftLint
              run: swiftlint lint --reporter github-actions-logging

            - name: Cancel wokflow on failure
              uses: andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a
              if: ${{ failure() }}
